# Generated by Django 5.2 on 2025-05-03 16:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oncoedu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ChemotherapyModalityRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Chemotherapy Modality Records',
            },
        ),
        migrations.CreateModel(
            name='ChemotherapyProtocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_observation_id', models.CharField(max_length=300)),
                ('cycle_no', models.BigIntegerField(blank=True, null=True)),
                ('type', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ChemotherapyProtocolRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Chemotherapy Protocol Records',
            },
        ),
        migrations.CreateModel(
            name='ClinicalResponseRateNewLesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Clinical Response Rate New Lesions',
            },
        ),
        migrations.CreateModel(
            name='ClinicalResponseRateNonTargetLesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Clinical Response Rate Non-Target Lesions',
            },
        ),
        migrations.CreateModel(
            name='ClinicalResponseRateResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Clinical Response Rate Results',
            },
        ),
        migrations.CreateModel(
            name='ClinicalResponseRateTargetLesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Clinical Response Rate Target Lesions',
            },
        ),
        migrations.CreateModel(
            name='ClockPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_observation_id', models.BigIntegerField()),
                ('side', models.CharField(blank=True, max_length=300, null=True)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ComorbidityRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Comorbidity Records',
            },
        ),
        migrations.CreateModel(
            name='ContraceptiveMethodRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contraceptive_methods', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Contraceptive Method Records',
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_observation_id', models.BigIntegerField()),
                ('detail', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Diagnosis',
            },
        ),
        migrations.CreateModel(
            name='DiagnosisDiseaseGroupRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Diagnosis Disease Group Records',
            },
        ),
        migrations.CreateModel(
            name='DiagnosisGroupRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Diagnosis Group Records',
            },
        ),
        migrations.CreateModel(
            name='DiagnosisLaterality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Diagnosis Laterality',
            },
        ),
        migrations.CreateModel(
            name='DiagnosisMetastaticSiteRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Diagnosis Metastastic Site Records',
            },
        ),
        migrations.CreateModel(
            name='DiagnosisPrimarySiteRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Diagnosis Primary Site Records',
            },
        ),
        migrations.CreateModel(
            name='DiseaseProgressionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Disease Progression Status',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ErStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('er_status', models.CharField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'ER Status',
            },
        ),
        migrations.CreateModel(
            name='Her2Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('her2_status', models.CharField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'HER2 Status',
            },
        ),
        migrations.CreateModel(
            name='HistopathologiesType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Histopathologies Type Records',
            },
        ),
        migrations.CreateModel(
            name='IHC_Chromogranin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'IHC-Chromogranin',
            },
        ),
        migrations.CreateModel(
            name='IHC_ER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'IHC-ER',
            },
        ),
        migrations.CreateModel(
            name='IHC_FISH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'IHC-FISH',
            },
        ),
        migrations.CreateModel(
            name='IHC_GATA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'IHC-GATA',
            },
        ),
        migrations.CreateModel(
            name='IHC_HER2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'IHC-HER2',
            },
        ),
        migrations.CreateModel(
            name='IHC_Others',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'IHC-Others',
            },
        ),
        migrations.CreateModel(
            name='IHC_PR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'IHC-PR',
            },
        ),
        migrations.CreateModel(
            name='IHC_Synaptophysin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'IHC-Synaptophysin',
            },
        ),
        migrations.CreateModel(
            name='IHCRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'IHC Records',
            },
        ),
        migrations.CreateModel(
            name='IHCResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'IHC Results',
            },
        ),
        migrations.CreateModel(
            name='Ki67Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ki67_status', models.CharField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'KI67 Status',
            },
        ),
        migrations.CreateModel(
            name='LineOfTreatmentRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Line of Treatment Records',
            },
        ),
        migrations.CreateModel(
            name='LuminalCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('results', models.CharField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Luminal Criteria',
            },
        ),
        migrations.CreateModel(
            name='MaritalStatusRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Marital Status Records',
            },
        ),
        migrations.CreateModel(
            name='MenstrualCycleRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Menstrual Cycle Records',
            },
        ),
        migrations.CreateModel(
            name='MolecularPathologies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_observation_id', models.BigIntegerField()),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Molecular Pathologies',
            },
        ),
        migrations.CreateModel(
            name='PastTreatmentHistories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_observation_id', models.BigIntegerField()),
                ('detail', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Past Treatment Histories',
            },
        ),
        migrations.CreateModel(
            name='Path_Ki67',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Path Ki67',
            },
        ),
        migrations.CreateModel(
            name='Path_lvsi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Path LVSI',
            },
        ),
        migrations.CreateModel(
            name='Path_Margin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Path Margin',
            },
        ),
        migrations.CreateModel(
            name='Path_Pni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Path PNI',
            },
        ),
        migrations.CreateModel(
            name='PathologicalResponseRateNewLesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Pathological Response Rate New Lesions',
            },
        ),
        migrations.CreateModel(
            name='PathologicalResponseRateNonTargetLesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Pathological Response Rate Non-Target Lesions',
            },
        ),
        migrations.CreateModel(
            name='PathologicalResponseRateResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Pathological Response Rate Results',
            },
        ),
        migrations.CreateModel(
            name='PathologicalResponseRateTargetLesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Pathological Response Rate Target Lesions',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=300)),
                ('phone', models.BigIntegerField(help_text='Phone number must be 11 digits', unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('nid', models.CharField(blank=True, max_length=25, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Female', 'Female'), ('Male', 'Male')], default='Female', max_length=10, null=True)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=10, null=True)),
                ('area', models.CharField(blank=True, max_length=300, null=True)),
                ('police_station', models.CharField(blank=True, max_length=300, null=True)),
                ('district', models.CharField(blank=True, max_length=300, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('passport', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PrStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_status', models.CharField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'PR Status',
            },
        ),
        migrations.CreateModel(
            name='RadiologicalResponseRateNewLesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Radiological Response Rate New Lesions',
            },
        ),
        migrations.CreateModel(
            name='RadiologicalResponseRateNonTargetLesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Rdiological Response Rate Non-Target Lesions',
            },
        ),
        migrations.CreateModel(
            name='RadiologicalResponseRateResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Radiological Response Rate Results',
            },
        ),
        migrations.CreateModel(
            name='RadiologicalResponseRateTargetLesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Radiological Response Rate Target Lesions',
            },
        ),
        migrations.CreateModel(
            name='RadiotherapyScheduleIntentRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RadiotherapyScheduleRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Radiotherapy Schedule Records',
            },
        ),
        migrations.CreateModel(
            name='ResponseRateType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Response Rate Types',
            },
        ),
        migrations.CreateModel(
            name='ScocioEconomicStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Socio Economic Status',
            },
        ),
        migrations.CreateModel(
            name='SurgeryModalityRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Surgery Modality Records',
            },
        ),
        migrations.CreateModel(
            name='SurvivalStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Survival Status',
            },
        ),
        migrations.CreateModel(
            name='TumourGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Tumour Grade',
            },
        ),
        migrations.CreateModel(
            name='ChemotherapyModalities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_observation_id', models.BigIntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oncoedu.chemotherapymodalityrecords')),
            ],
            options={
                'verbose_name_plural': 'Chemotherapy Modalities',
            },
        ),
        migrations.CreateModel(
            name='ChemotherapyProtocolDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('chemotherapy_protocol_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oncoedu.chemotherapyprotocol')),
            ],
            options={
                'verbose_name_plural': 'Chemotherapy Protocol Details',
            },
        ),
        migrations.CreateModel(
            name='ClinicalResponseRateCalculationRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('new_lesion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinical_response_rate_new_lesion', to='oncoedu.clinicalresponseratenewlesion')),
                ('target_lesion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinical_response_rate_target_lesion', to='oncoedu.clinicalresponseratenewlesion')),
                ('non_target_lesion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinical_response_rate_non_target_lesion', to='oncoedu.clinicalresponseratenontargetlesion')),
                ('result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinical_response_rate_result', to='oncoedu.clinicalresponserateresult')),
            ],
            options={
                'verbose_name_plural': 'Clinical Response Rate Calculation Records',
            },
        ),
        migrations.CreateModel(
            name='Comorbidity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_observation_id', models.BigIntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oncoedu.comorbidityrecords')),
            ],
            options={
                'verbose_name_plural': 'Comorbidities',
            },
        ),
        migrations.CreateModel(
            name='DiagnosisDiseaseSubGroupRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('diagnosis_disease_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oncoedu.diagnosisdiseasegrouprecords')),
            ],
            options={
                'verbose_name_plural': 'Diagnosis Disease Sub Group Records',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('phone', models.BigIntegerField(blank=True, help_text='Phone number must be 11 digits', null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('designation', models.CharField(blank=True, max_length=300, null=True)),
                ('department', models.CharField(blank=True, max_length=300, null=True)),
                ('institution', models.CharField(blank=True, max_length=300, null=True)),
                ('bmdc_number', models.CharField(blank=True, max_length=300, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('center_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oncoedu.center')),
            ],
        ),
        migrations.CreateModel(
            name='HistopathologyRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oncoedu.histopathologiestype')),
            ],
            options={
                'verbose_name_plural': 'Histopathology Records',
            },
        ),
        migrations.CreateModel(
            name='IHC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_observation_id', models.BigIntegerField()),
                ('date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Chromogranin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oncoedu.ihc_chromogranin')),
                ('ER', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oncoedu.ihc_er')),
                ('FISH', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oncoedu.ihc_fish')),
                ('GATA', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oncoedu.ihc_gata')),
                ('HER2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oncoedu.ihc_her2')),
                ('others', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oncoedu.ihc_others')),
                ('PR', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oncoedu.ihc_pr')),
                ('Synaptophysin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oncoedu.ihc_synaptophysin')),
            ],
            options={
                'verbose_name_plural': 'IHC',
            },
        ),
        migrations.CreateModel(
            name='PathologicalResponseRateCalculationRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('new_lesion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pathological_response_rate_new_lesion', to='oncoedu.pathologicalresponseratenewlesion')),
                ('target_lesion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pathological_response_rate_target_lesion', to='oncoedu.pathologicalresponseratenewlesion')),
                ('non_target_lesion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pathological_response_rate_non_target_lesion', to='oncoedu.pathologicalresponseratenontargetlesion')),
                ('result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pathological_response_rate_result', to='oncoedu.pathologicalresponserateresult')),
            ],
            options={
                'verbose_name_plural': 'Pathological Response Rate Calculation Records',
            },
        ),
        migrations.CreateModel(
            name='DoctorPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('doctor_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oncoedu.doctor')),
                ('patient_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oncoedu.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PatientHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_observation_id', models.BigIntegerField()),
                ('family_member', models.IntegerField(blank=True, null=True)),
                ('age_of_marriage', models.IntegerField(blank=True, null=True)),
                ('age_of_first_child', models.IntegerField(blank=True, null=True)),
                ('age_of_menarche', models.IntegerField(blank=True, null=True)),
                ('age_of_menopause', models.IntegerField(blank=True, null=True)),
                ('breast_examination', models.CharField(blank=True, choices=[('Self Examination', 'Self Examination'), ('Clinical Examination', 'Clinical Examination'), ('Mammogram', 'Mammogram'), ('Ultrasound', 'Ultrasound')], max_length=300, null=True)),
                ('excercise_per_week', models.IntegerField(blank=True, help_text='Number of excercise per week in hours', null=True)),
                ('dietary_habit', models.CharField(blank=True, max_length=300, null=True)),
                ('height', models.FloatField(blank=True, help_text='Height in cm', null=True)),
                ('weight', models.FloatField(blank=True, help_text='Weight in kg', null=True)),
                ('bmi', models.FloatField(blank=True, help_text='BMI = weight(kg) / height(m)^2', null=True)),
                ('h_o_alcholism', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=300, null=True)),
                ('h_o_hrt', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=300, null=True)),
                ('breast_feeding_duration', models.IntegerField(blank=True, help_text='Breast feeding duration in months', null=True)),
                ('rt_to_chest', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=300, null=True)),
                ('cancer_history', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=300, null=True)),
                ('known_mutation', models.CharField(blank=True, max_length=300, null=True)),
                ('first_diagnosis_date', models.DateField(blank=True, null=True)),
                ('smoking_history', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=300, null=True)),
                ('smoking_packets_per_year', models.IntegerField(blank=True, help_text='Number of packets smoked per year', null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('breast_examination_value', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oncoedu.breastexaminationvaluerecord')),
                ('contraceptive_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oncoedu.contraceptivemethodrecords')),
                ('marital_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oncoedu.maritalstatusrecords')),
                ('regular_irregular_menstruation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oncoedu.menstrualcyclerecords')),
            ],
            options={
                'verbose_name_plural': 'Patient Histories',
            },
        ),
        migrations.CreateModel(
            name='PFSStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_observation_id', models.BigIntegerField()),
                ('date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oncoedu.diseaseprogressionstatus')),
            ],
            options={
                'verbose_name_plural': 'PFS Status',
            },
        ),
        migrations.CreateModel(
            name='PoliceStations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oncoedu.district')),
            ],
            options={
                'verbose_name_plural': 'Police Stations',
            },
        ),
        migrations.CreateModel(
            name='DiagnosisGroupCalculationRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('er', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oncoedu.erstatus')),
                ('her2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oncoedu.her2status')),
                ('ki67', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oncoedu.ki67status')),
                ('results', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oncoedu.luminalcriteria')),
                ('pr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oncoedu.prstatus')),
            ],
            options={
                'verbose_name_plural': 'Diagnosis Group Calculation Records',
            },
        ),
        migrations.CreateModel(
            name='DiagnosisGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_observation_id', models.BigIntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('er', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oncoedu.erstatus')),
                ('her2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oncoedu.her2status')),
                ('ki67', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oncoedu.ki67status')),
                ('result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oncoedu.luminalcriteria')),
                ('pr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oncoedu.prstatus')),
            ],
            options={
                'verbose_name_plural': 'Diagnosis Groups',
            },
        ),
        migrations.CreateModel(
            name='RadiologicalResponseRateCalculationRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('new_lesion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='radiological_response_rate_new_lesion', to='oncoedu.radiologicalresponseratenewlesion')),
                ('target_lesion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='radiological_response_rate_target_lesion', to='oncoedu.radiologicalresponseratenewlesion')),
                ('non_target_lesion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='radiological_response_rate_non_target_lesion', to='oncoedu.radiologicalresponseratenontargetlesion')),
                ('result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='radiological_response_rate_result', to='oncoedu.radiologicalresponserateresult')),
            ],
            options={
                'verbose_name_plural': 'Radiological Response Rate Calculation Records',
            },
        ),
        migrations.CreateModel(
            name='RadiotherapySchedules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_observation_id', models.BigIntegerField()),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('intent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oncoedu.radiotherapyscheduleintentrecords')),
            ],
            options={
                'verbose_name_plural': 'Radiotherapy Schedules',
            },
        ),
        migrations.CreateModel(
            name='RadiotherapyScheduleDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('radiotherapy_schedule_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oncoedu.radiotherapyschedules')),
            ],
            options={
                'verbose_name_plural': 'Radiotherapy Schedule Details',
            },
        ),
        migrations.AddField(
            model_name='patient',
            name='socio_economic_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oncoedu.scocioeconomicstatus'),
        ),
        migrations.CreateModel(
            name='StagingPathologicalsDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_observation_id', models.BigIntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('ki67', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oncoedu.path_ki67')),
                ('lvsi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oncoedu.path_lvsi')),
                ('margin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oncoedu.path_margin')),
                ('pni', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oncoedu.path_pni')),
            ],
            options={
                'verbose_name_plural': 'Staging Pathologicals Details',
            },
        ),
        migrations.CreateModel(
            name='Surgeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_observation_id', models.BigIntegerField()),
                ('surgery_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('modality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oncoedu.surgerymodalityrecords')),
            ],
            options={
                'verbose_name_plural': 'Surgeries',
            },
        ),
        migrations.CreateModel(
            name='OSStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_observation_id', models.BigIntegerField()),
                ('date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oncoedu.survivalstatus')),
            ],
            options={
                'verbose_name_plural': 'OS Status',
            },
        ),
        migrations.CreateModel(
            name='PatientObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('registration_number', models.CharField(blank=True, max_length=300, null=True)),
                ('laterality', models.CharField(blank=True, max_length=300, null=True)),
                ('current_chemo_protocol', models.TextField(blank=True, null=True)),
                ('chemo_starting_date', models.DateField(blank=True, null=True)),
                ('chemo_cycle_no', models.IntegerField(blank=True, null=True)),
                ('chemo_detail', models.TextField(blank=True, null=True)),
                ('disease_progression_status_date', models.DateField(blank=True, null=True)),
                ('survival_status_date', models.DateField(blank=True, null=True)),
                ('clinical_response_rate_date', models.DateField(blank=True, null=True)),
                ('radiological_response_rate_date', models.DateField(blank=True, null=True)),
                ('pathological_response_rate_date', models.DateField(blank=True, null=True)),
                ('cancer_type', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('center_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='oncoedu.center')),
                ('clinical_response_rate_new_lasion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinical_new_observations', to='oncoedu.clinicalresponseratenewlesion')),
                ('clinical_response_rate_non_target_lasion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinical_non_target_observations', to='oncoedu.clinicalresponseratenontargetlesion')),
                ('clinical_response_rate_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinical_result_observations', to='oncoedu.clinicalresponserateresult')),
                ('clinical_response_rate_target_lasion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinical_target_observations', to='oncoedu.clinicalresponseratetargetlesion')),
                ('diagnosis_disease_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_observations', to='oncoedu.diagnosisdiseasegrouprecords')),
                ('diagnosis_laterility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='laterality_observations', to='oncoedu.diagnosislaterality')),
                ('diagnosis_primary_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_observations', to='oncoedu.diagnosisprimarysiterecords')),
                ('diagnosis_subgroup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_observations', to='oncoedu.diagnosisdiseasesubgrouprecords')),
                ('disease_progression_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_observations', to='oncoedu.diseaseprogressionstatus')),
                ('doctor_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='oncoedu.doctor')),
                ('line_of_treatment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_observations', to='oncoedu.lineoftreatmentrecords')),
                ('overall_survival', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_observations', to='oncoedu.osstatus')),
                ('pathological_response_rate_new_lasion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pathological_new_observations', to='oncoedu.pathologicalresponseratenewlesion')),
                ('pathological_response_rate_non_target_lasion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pathological_non_target_observations', to='oncoedu.pathologicalresponseratenontargetlesion')),
                ('pathological_response_rate_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pathological_result_observations', to='oncoedu.pathologicalresponserateresult')),
                ('pathological_response_rate_target_lasion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pathological_target_observations', to='oncoedu.pathologicalresponseratetargetlesion')),
                ('patient_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='oncoedu.patient')),
                ('pfs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_observations', to='oncoedu.pfsstatus')),
                ('radiological_response_rate_new_lasion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='radiological_new_observations', to='oncoedu.radiologicalresponseratenewlesion')),
                ('radiological_response_rate_non_target_lasion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='radiological_non_target_observations', to='oncoedu.radiologicalresponseratenontargetlesion')),
                ('radiological_response_rate_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='radiological_result_observations', to='oncoedu.radiologicalresponserateresult')),
                ('radiological_response_rate_target_lasion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='radiological_target_observations', to='oncoedu.radiologicalresponseratetargetlesion')),
                ('survival_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_observations', to='oncoedu.survivalstatus')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_observations', to='oncoedu.tumourgrade')),
            ],
            options={
                'verbose_name_plural': 'Patient Observations',
            },
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.UniqueConstraint(condition=models.Q(('email', None), _negated=True), fields=('email',), name='unique_email_not_null'),
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.UniqueConstraint(condition=models.Q(('nid', None), _negated=True), fields=('nid',), name='unique_nid_not_null'),
        ),
    ]
