# Generated by Django 5.2 on 2025-05-04 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oncoedu', '0002_center_chemotherapymodalityrecords_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancermarker',
            name='patient_observation_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oncoedu.patientobservation'),
        ),
        migrations.AlterField(
            model_name='chemotherapymodalities',
            name='patient_observation_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oncoedu.patientobservation'),
        ),
        migrations.AlterField(
            model_name='chemotherapyprotocol',
            name='patient_observation_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oncoedu.patientobservation'),
        ),
        migrations.AlterField(
            model_name='clockposition',
            name='patient_observation_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oncoedu.patientobservation'),
        ),
        migrations.AlterField(
            model_name='comorbidity',
            name='patient_observation_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oncoedu.patientobservation'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='patient_observation_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oncoedu.patientobservation'),
        ),
        migrations.AlterField(
            model_name='diagnosisgroup',
            name='patient_observation_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oncoedu.patientobservation'),
        ),
        migrations.AlterField(
            model_name='ihc',
            name='patient_observation_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oncoedu.patientobservation'),
        ),
        migrations.AlterField(
            model_name='molecularpathologies',
            name='patient_observation_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oncoedu.patientobservation'),
        ),
        migrations.AlterField(
            model_name='osstatus',
            name='patient_observation_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oncoedu.patientobservation'),
        ),
        migrations.AlterField(
            model_name='pasttreatmenthistories',
            name='patient_observation_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oncoedu.patientobservation'),
        ),
        migrations.AlterField(
            model_name='patienthistory',
            name='patient_observation_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oncoedu.patientobservation'),
        ),
        migrations.AlterField(
            model_name='pfsstatus',
            name='patient_observation_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oncoedu.patientobservation'),
        ),
        migrations.AlterField(
            model_name='radiotherapyschedules',
            name='patient_observation_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oncoedu.patientobservation'),
        ),
        migrations.AlterField(
            model_name='stagingpathologicalsdetails',
            name='patient_observation_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oncoedu.patientobservation'),
        ),
        migrations.AlterField(
            model_name='surgeries',
            name='patient_observation_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oncoedu.patientobservation'),
        ),
    ]
