# Generated by Django 5.2 on 2025-05-05 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oncoedu', '0005_alter_radiotherapyscheduleintentrecords_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalresponseratecalculationrecords',
            name='target_lesion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinical_response_rate_target_lesion', to='oncoedu.clinicalresponseratetargetlesion'),
        ),
        migrations.AlterField(
            model_name='pathologicalresponseratecalculationrecords',
            name='target_lesion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pathological_response_rate_target_lesion', to='oncoedu.pathologicalresponseratetargetlesion'),
        ),
        migrations.AlterField(
            model_name='radiologicalresponseratecalculationrecords',
            name='target_lesion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='radiological_response_rate_target_lesion', to='oncoedu.radiologicalresponseratetargetlesion'),
        ),
    ]
