# Generated by Django 5.2 on 2025-05-05 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oncoedu', '0006_alter_clinicalresponseratecalculationrecords_target_lesion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalTNMStagingM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Clinical TNM Staging-M',
            },
        ),
        migrations.CreateModel(
            name='ClinicalTNMStagingN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Clinical TNM Staging-N',
            },
        ),
        migrations.CreateModel(
            name='ClinicalTNMStagingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'TNM Staging Results',
            },
        ),
        migrations.CreateModel(
            name='ClinicalTNMStagingT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Clinical TNM Staging-T',
            },
        ),
        migrations.CreateModel(
            name='PathologicalTNMStagingM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Pathological TNM Staging-M',
            },
        ),
        migrations.CreateModel(
            name='PathologicalTNMStagingN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Pathological TNM Staging-N',
            },
        ),
        migrations.CreateModel(
            name='PathologicalTNMStagingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Pathological TNM Staging Results',
            },
        ),
        migrations.CreateModel(
            name='PathologicalTNMStagingT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Pathological TNM Staging-T',
            },
        ),
        migrations.AlterField(
            model_name='osstatus',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='osstatus',
            name='updated_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='pfsstatus',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='pfsstatus',
            name='updated_at',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='ClinicalTNMStagingCalculationRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('m', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clinical_tnm_staging_m', to='oncoedu.clinicaltnmstagingm')),
                ('n', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clinical_tnm_staging_n', to='oncoedu.clinicaltnmstagingn')),
                ('result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clinical_tnm_staging_result', to='oncoedu.clinicaltnmstagingresult')),
                ('t', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clinical_tnm_staging_t', to='oncoedu.clinicaltnmstagingt')),
            ],
            options={
                'verbose_name_plural': 'Clinical TNM Staging Calculation Records',
            },
        ),
        migrations.CreateModel(
            name='PathologicalTNMStagingCalculationRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('m', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pathological_tnm_staging_m', to='oncoedu.pathologicaltnmstagingm')),
                ('n', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pathological_tnm_staging_n', to='oncoedu.pathologicaltnmstagingn')),
                ('result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pathological_tnm_staging_result', to='oncoedu.pathologicaltnmstagingresult')),
                ('t', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pathological_tnm_staging_t', to='oncoedu.pathologicaltnmstagingt')),
            ],
            options={
                'verbose_name_plural': 'Pathological TNM Staging Calculation Records',
            },
        ),
        migrations.CreateModel(
            name='StagingClinicals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('m', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clinical_m_staging', to='oncoedu.clinicaltnmstagingm')),
                ('n', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clinical_n_staging', to='oncoedu.clinicaltnmstagingn')),
                ('patient_observation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oncoedu.patientobservation')),
                ('result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clinical_result_staging', to='oncoedu.clinicaltnmstagingresult')),
                ('t', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clinical_t_staging', to='oncoedu.clinicaltnmstagingt')),
            ],
            options={
                'verbose_name_plural': 'Staging Clinicals',
            },
        ),
        migrations.CreateModel(
            name='StagingPathologicals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('m', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pathological_m_staging', to='oncoedu.pathologicaltnmstagingm')),
                ('n', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pathological_n_staging', to='oncoedu.pathologicaltnmstagingn')),
                ('patient_observation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oncoedu.patientobservation')),
                ('result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pathological_result_staging', to='oncoedu.pathologicaltnmstagingresult')),
                ('t', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pathological_t_staging', to='oncoedu.pathologicaltnmstagingt')),
            ],
            options={
                'verbose_name_plural': 'Staging Pathologicals',
            },
        ),
    ]
