# Generated by Django 5.2 on 2025-05-05 16:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oncoedu', '0007_clinicaltnmstagingm_clinicaltnmstagingn_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clinicaltnmstagingresult',
            options={'verbose_name_plural': 'Clinical TNM Staging Results'},
        ),
        migrations.AddField(
            model_name='patientobservation',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_observations', to='oncoedu.tumourgrade'),
        ),
        migrations.AddField(
            model_name='patientobservation',
            name='laterality',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='patientobservation',
            name='registration_number',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='patientobservation',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='clinicaltnmstagingcalculationrecords',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='clinicaltnmstagingcalculationrecords',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pathologicaltnmstagingcalculationrecords',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pathologicaltnmstagingcalculationrecords',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
