# Generated by Django 5.2 on 2025-05-05 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oncoedu', '0008_alter_clinicaltnmstagingresult_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientobservation',
            name='cancer_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patientobservation',
            name='chemo_cycle_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientobservation',
            name='chemo_detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientobservation',
            name='chemo_starting_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientobservation',
            name='clinical_response_rate_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientobservation',
            name='clinical_response_rate_new_lasion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinical_new_observations', to='oncoedu.clinicalresponseratenewlesion'),
        ),
        migrations.AddField(
            model_name='patientobservation',
            name='clinical_response_rate_non_target_lasion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinical_non_target_observations', to='oncoedu.clinicalresponseratenontargetlesion'),
        ),
        migrations.AddField(
            model_name='patientobservation',
            name='clinical_response_rate_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinical_result_observations', to='oncoedu.clinicalresponserateresult'),
        ),
        migrations.AddField(
            model_name='patientobservation',
            name='clinical_response_rate_target_lasion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinical_target_observations', to='oncoedu.clinicalresponseratetargetlesion'),
        ),
        migrations.AddField(
            model_name='patientobservation',
            name='current_chemo_protocol',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientobservation',
            name='diagnosis_disease_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_observations', to='oncoedu.diagnosisdiseasegrouprecords'),
        ),
        migrations.AddField(
            model_name='patientobservation',
            name='diagnosis_laterility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='laterality_observations', to='oncoedu.diagnosislaterality'),
        ),
        migrations.AddField(
            model_name='patientobservation',
            name='diagnosis_primary_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_observations', to='oncoedu.diagnosisprimarysiterecords'),
        ),
        migrations.AddField(
            model_name='patientobservation',
            name='diagnosis_subgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_observations', to='oncoedu.diagnosisdiseasesubgrouprecords'),
        ),
        migrations.AddField(
            model_name='patientobservation',
            name='disease_progression_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_observations', to='oncoedu.diseaseprogressionstatus'),
        ),
        migrations.AddField(
            model_name='patientobservation',
            name='disease_progression_status_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientobservation',
            name='line_of_treatment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_observations', to='oncoedu.lineoftreatmentrecords'),
        ),
        migrations.AddField(
            model_name='patientobservation',
            name='overall_survival',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_observations', to='oncoedu.osstatus'),
        ),
        migrations.AddField(
            model_name='patientobservation',
            name='pathological_response_rate_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientobservation',
            name='pathological_response_rate_new_lasion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pathological_new_observations', to='oncoedu.pathologicalresponseratenewlesion'),
        ),
        migrations.AddField(
            model_name='patientobservation',
            name='pathological_response_rate_non_target_lasion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pathological_non_target_observations', to='oncoedu.pathologicalresponseratenontargetlesion'),
        ),
        migrations.AddField(
            model_name='patientobservation',
            name='pathological_response_rate_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pathological_result_observations', to='oncoedu.pathologicalresponserateresult'),
        ),
        migrations.AddField(
            model_name='patientobservation',
            name='pathological_response_rate_target_lasion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pathological_target_observations', to='oncoedu.pathologicalresponseratetargetlesion'),
        ),
        migrations.AddField(
            model_name='patientobservation',
            name='pfs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_observations', to='oncoedu.pfsstatus'),
        ),
        migrations.AddField(
            model_name='patientobservation',
            name='radiological_response_rate_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientobservation',
            name='radiological_response_rate_new_lasion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='radiological_new_observations', to='oncoedu.radiologicalresponseratenewlesion'),
        ),
        migrations.AddField(
            model_name='patientobservation',
            name='radiological_response_rate_non_target_lasion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='radiological_non_target_observations', to='oncoedu.radiologicalresponseratenontargetlesion'),
        ),
        migrations.AddField(
            model_name='patientobservation',
            name='radiological_response_rate_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='radiological_result_observations', to='oncoedu.radiologicalresponserateresult'),
        ),
        migrations.AddField(
            model_name='patientobservation',
            name='radiological_response_rate_target_lasion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='radiological_target_observations', to='oncoedu.radiologicalresponseratetargetlesion'),
        ),
        migrations.AddField(
            model_name='patientobservation',
            name='survival_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_observations', to='oncoedu.survivalstatus'),
        ),
        migrations.AddField(
            model_name='patientobservation',
            name='survival_status_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
