# Generated by Django 5.2 on 2025-05-05 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oncoedu', '0009_patientobservation_cancer_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientobservation',
            name='overall_survival',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientobservation',
            name='pfs',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
