# Generated by Django 5.2 on 2025-05-06 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oncoedu', '0010_alter_patientobservation_overall_survival_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancer_marker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oncoedu.cancermarker')),
                ('chemotherapy_modalities', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oncoedu.chemotherapymodalities')),
                ('chemotherapy_protocol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oncoedu.chemotherapyprotocol')),
                ('clock_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oncoedu.clockposition')),
                ('comorbidity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oncoedu.comorbidity')),
                ('diagnosis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oncoedu.diagnosis')),
                ('diagnosis_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oncoedu.diagnosisgroup')),
                ('ihc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oncoedu.ihc')),
                ('molecular_pathologies', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oncoedu.molecularpathologies')),
                ('os_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oncoedu.osstatus')),
                ('past_treatment_histories', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oncoedu.pasttreatmenthistories')),
                ('patient_history', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oncoedu.patienthistory')),
                ('patient_observation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='oncoedu.patientobservation')),
                ('pfs_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oncoedu.pfsstatus')),
                ('radiotherapy_schedules', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oncoedu.radiotherapyschedules')),
                ('staging_clinicals', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oncoedu.stagingclinicals')),
                ('staging_pathologicals', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oncoedu.stagingpathologicals')),
                ('staging_pathologicals_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oncoedu.stagingpathologicalsdetails')),
                ('surgeries', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oncoedu.surgeries')),
            ],
        ),
    ]
