from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import *
router = DefaultRouter()
router.register(r'cancer-markers', CancerMarkerViewSet)
router.register(r'patient', PatientViewSet)
router.register(r'patient-observation', PatientObservationViewSet)
router.register(r'breast-examination-value-records', BreastExaminationValueRecordViewSet)
router.register(r'cancer-marker-records', CancerMarkerRecordsViewSet)
router.register(r'socio-economic-status', ScocioEconomicStatusViewSet)
router.register(r'centers', CenterViewSet)
router.register(r'districts', DistrictViewSet)
router.register(r'police-stations', PoliceStationsViewSet)
router.register(r'chemotherapy-modality-records', ChemotherapyModalityRecordsViewSet)
router.register(r'chemotherapy-protocol-records', ChemotherapyProtocolRecordsViewSet)
router.register(r'diagnosis-laterality', DiagnosisLateralityViewSet)
router.register(r'diagnosis-disease-group-records', DiagnosisDiseaseGroupRecordsViewSet)
router.register(r'diagnosis-disease-subgroup-records', DiagnosisDiseaseSubGroupRecordsViewSet)
router.register(r'diagnosis-group-records', DiagnosisGroupRecordsViewSet)
router.register(r'er-status', ErStatusViewSet)
router.register(r'pr-status', PrStatusViewSet)
router.register(r'her2-status', Her2StatusViewSet)
router.register(r'ki67-status', Ki67StatusViewSet)
router.register(r'luminal-criteria', LuminalCriteriaViewSet)
router.register(r'diagnosis-primary-site-records', DiagnosisPrimarySiteRecordsViewSet)
router.register(r'diagnosis-metastatic-site-records', DiagnosisMetastaticSiteRecordsViewSet)
router.register(r'histopathologies-type', HistopathologiesTypeViewSet)
router.register(r'histopathology-records', HistopathologyRecordsViewSet)
router.register(r'line-of-treatment-records', LineOfTreatmentRecordsViewSet)
router.register(r'marital-status-records', MaritalStatusRecordsViewSet)
router.register(r'menstrual-cycle-records', MenstrualCycleRecordsViewSet)
router.register(r'radiotherapy-schedule-intent-records', RadiotherapyScheduleIntentRecordsViewSet)
router.register(r'radiotherapy-schedule-records', RadiotherapyScheduleRecordsViewSet)
router.register(r'surgery-modality-records', SurgeryModalityRecordsViewSet)
router.register(r'ihc-records', IHCRecordsViewSet)
router.register(r'ihc-results', IHCResultsViewSet)
router.register(r'ihc-er', IHC_ERViewSet)
router.register(r'ihc-pr', IHC_PRViewSet)
router.register(r'ihc-her2', IHC_HER2ViewSet)
router.register(r'ihc-fish', IHC_FISHViewSet)
router.register(r'ihc-synaptophysin', IHC_SynaptophysinViewSet)
router.register(r'ihc-chromogranin', IHC_ChromograninViewSet)
router.register(r'ihc-gata', IHC_GATAViewSet)
router.register(r'ihc-others', IHC_OthersViewSet)
router.register(r'path-lvsi', Path_lvsiViewSet)
router.register(r'path-pni', Path_PniViewSet)
router.register(r'path-margin', Path_MarginViewSet)
router.register(r'path-ki67', Path_Ki67ViewSet)
router.register(r'tumour-grade', TumourGradeViewSet)
router.register(r'disease-progression-status', DiseaseProgressionStatusViewSet)
router.register(r'survival-status', SurvivalStatusViewSet)
router.register(r'response-rate-type', ResponseRateTypeViewSet)
router.register(r'clinical-response-rate-target-lesion', ClinicalResponseRateTargetLesionViewSet)
router.register(r'pathological-response-rate-target-lesion', PathologicalResponseRateTargetLesionViewSet)
router.register(r'radiological-response-rate-target-lesion', RadiologicalResponseRateTargetLesionViewSet)
router.register(r'clinical-response-rate-non-target-lesion', ClinicalResponseRateNonTargetLesionViewSet)
router.register(r'pathological-response-rate-non-target-lesion', PathologicalResponseRateNonTargetLesionViewSet)
router.register(r'radiological-response-rate-non-target-lesion', RadiologicalResponseRateNonTargetLesionViewSet)
router.register(r'clinical-response-rate-new-lesion', ClinicalResponseRateNewLesionViewSet)
router.register(r'pathological-response-rate-new-lesion', PathologicalResponseRateNewLesionViewSet)
router.register(r'radiological-response-rate-new-lesion', RadiologicalResponseRateNewLesionViewSet)
router.register(r'clinical-response-rate-result', ClinicalResponseRateResultViewSet)
router.register(r'pathological-response-rate-result', PathologicalResponseRateResultViewSet)
router.register(r'radiological-response-rate-result', RadiologicalResponseRateResultViewSet)
router.register(r'clinical-tnm-staging-t', ClinicalTNMStagingTViewSet)
router.register(r'clinical-tnm-staging-n', ClinicalTNMStagingNViewSet)
router.register(r'clinical-tnm-staging-m', ClinicalTNMStagingMViewSet)
router.register(r'clinical-tnm-staging-result', ClinicalTNMStagingResultViewSet)
router.register(r'pathological-tnm-staging-t', PathologicalTNMStagingTViewSet)
router.register(r'pathological-tnm-staging-n', PathologicalTNMStagingNViewSet)
router.register(r'pathological-tnm-staging-m', PathologicalTNMStagingMViewSet)
router.register(r'pathological-tnm-staging-result', PathologicalTNMStagingResultViewSet)
router.register(r'chemotherapy-Modalities', ChemotherapyModalitiesSerializerView)
router.register(r'chemotherapy-Protocol', ChemotherapyProtocolSerializerView)
router.register(r'clock-position', ClockPositionSerializerView)
router.register(r'comorbidity', ComorbidityView)
router.register(r'diagnosis', DiagnosisView)
router.register(r'molecular-pathology', MolecularPathologiesSerializerView)
router.register(r'past-treatment-histories', PastTreatmentHistoriesSerializerView)
router.register(r'patient-histories', PatientHistorySerializerView)
router.register(r'radiotherapy-schedules', RadiotherapySchedulesSerializerView)
router.register(r'surgeries', SurgeriesSerializerView)
router.register(r'IHC', IHCSerializerView)
router.register(r'staging-pathological-details', StagingPathologicalsDetailsSerializerView)
router.register(r'pfs-status', PFSStatusSerializerView)
router.register(r'os-status', OSStatusSerializerView)
router.register(r'staging-clinicals', StagingClinicalsSerializerView)
router.register(r'staging-pathologicals', StagingPathologicalsSerializerView)
router.register(r'all-data', AllDataSerializerView)
router.register(r'doctor', DoctorView)
router.register(r'contraceptive-methods-records', ContraceptiveMethodRecordsViewSet)
router.register(r'comorbidity-records', ComobidityRecordsView)







urlpatterns = [
    path('api/', include(router.urls)),
]
